name: todo_list
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  http: 
  introduction_screen: ^3.0.0
  cupertino_icons: ^1.0.8
  uuid: ^4.5.1
  shared_preferences: ^2.3.3
  sqflite: ^2.4.1
  path: ^1.9.0
  sqflite_common_ffi: ^2.0.0
  provider: ^6.1.2






dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.4.3

  flutter_lints: ^4.0.0


flutter:

  uses-material-design: true
  assets:
    - assets/intro/icons8-todoist-500.png

  fonts:
    - family: intro
      fonts:
        - asset: assets/fonts/BebasNeue-Regular.ttf